# Generated by Django 2.0.5 on 2018-05-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello', models.TextField()),
                ('helloworld', models.CharField(default='pozalabs', max_length=20)),
            ],
        ),
    ]
